limetypes:
  solutionimprovement:
    title: title
    priority: priority
    misc: misc
    comment: comment
    status: solutionimprovementstatus
    # name: title

    
    lanes:
    card:
      title: 
      status:
      priority:

  deal:
    name:
    
        
  other_limetype_example:
   solution_improvement_config:
    title:
    lanes:
      - chill
      - less chill
      - urgent
    card:
      title: 
      status:
      priority:
      customfields:
        - blablafield:
