# TODO: Handle priority, handle DateTime (possible?)
#
# Here you can define custom limetypes to be presented.
# The structure is as follows:
#   example_limetype: 
#     presentation_alias: database_key
#
# Special keywords: 
#   title    - This will become the title (header) of the item.
#   priority - This decides the order of the items on the on the horizontal axis. (WIP) 
limetypes:
  solutionimprovement:
    title: title
    priority: priority
    misc: misc
    comment: comment
    status: solutionimprovementstatus
    # donedate: donedate // DateTime not serializable error ?

  deal:
    title: name
    priority: probability
    misc: value
    comment: wonlostreason
    status: dealstatus

  company:
    title: name
    priority: buyingstatus 

  todo:
    title: subject
    comment: note
    priority: location  
    # starttime: starttime // DateTime not serializable error?

  campaign:
    title: name
    priority: campaignstatus
    type: type
    purpose: purpose
    goal: goal
    workmode: workmode

