limetypes:
  solutionimprovement:
    title: title
    priority: priority
    misc: misc
    comment: comment
    status: solutionimprovementstatus
    # donedate: donedate // DateTime not serializable error ?

  deal:
    title: name
    priority: probability
    misc: value
    comment: wonlostreason
    status: dealstatus

  company:
    title: name
    priority: buyingstatus 

  todo:
    title: subject
    comment: note
    priority: location # ? 
    # starttime: starttime // DateTime not serializable error?

  campaign:
    title: name
    priority: campaignstatus
    type: type
    purpose: purpose
    goal: goal
    workmode: workmode

