# TODO: Handle priority, handle DateTime (possible?)
#
# Here you can define custom limetypes to be presented.
# The structure is as follows:
#   example_limetype: 
#     presentation_alias: database_key
#
# Special keywords: 
#   title          - This will become the title (header) of the item. (required)
#   secondary_text - This will be displayed underneath the header. (not required) 
#   status         - This decides the order of the items on the on the horizontal axis. (WIP) 
#   
limetypes:
  solutionimprovement:
    title: title
    Secondary Text: comment
    # priority: priority
    misc: misc
    status: solutionimprovementstatus
    # donedate: donedate # DateTime not serializable error ?
    prio:
      deny: 1
      More info needed: 2
      reported: 3
      started: 4
      approved: 5
      done: 6
      
  deal:
    title: name
    priority: probability
    value: value
    wonlostreason: wonlostreason
    status: dealstatus
    prio:
      contact: 1
      requirement: 2
      tender: 3
      agreement: 4
      rejection: 5
      onhold: 6

  company:
    title: name
    priority: buyingstatus 

  todo:
    title: subject
    priority: location  
    comment: note
    # starttime: starttime # DateTime not serializable error?

  campaign:
    title: name
    priority: campaignstatus
    type: type
    purpose: purpose
    goal: goal
    workmode: workmode

